server:
  port: 8080

spring:
  application:
    name: demo-app-gateway-service
  cloud:
    gateway:
      routes:
        - id: orders
          uri: http://localhost:8001
          predicates: Path=/orders/**
        - id: products
          uri: http://localhost:8002
          predicates: Path=/products/**
        - id: profile
          uri: http://localhost:8003
          predicates: Path=/profile/**

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
